### ISSUE TITLE
http://localhost:8000/phpmyadmin 顯示 The requested URL /phpmyadmin was not found on this server.

### ISSUE THREAD

**Issue by KOEI5113** [laravel-dojo/wagon#5]
您好，我根據 http://www.laravel-dojo.com/workshops/201505-nutc#chapter1 的投影片在實作，
但是自 http://www.laravel-dojo.com/opensource/wagon 所下載的 wagon, 
開啟後輸入投影片上的 http://localhost:8000/phpmyadmin 
會顯示 The requested URL /phpmyadmin was not found on this server.

想確認是有需要做什麼額外設定嗎

**Comment by shengyou** [comment]
您看的這份文件太舊了，因為 UwAmp 裡的 phpmyadmin 被我換成比較輕量的 adminer 了。麻煩您試一下 http://localhost:8000/mysql 或 http://localhost:8000/adminer 應該就可以正常看到登入畫面。登入時 Host 請用 localhost:33060

**Comment by KOEI5113** [comment]
嗨，非常感謝你的回覆！
想確認那如果要使用 phpmyadmin 作資料庫管理，該怎麼把 phpmyadmin 灌起來呢 ?
第一次使用 Wagon 不太確定該怎麼進行...

**Comment by shengyou** [comment]
那我會建議您直接去 UwAmp 官網下載原始的版本，再把 wagon 裡的版本蓋過去即可。因為官網原始版本內建是使用 phpmyadmin 來做資料庫 Client。 :)
