### ISSUE TITLE
mysql 無法Stop 解決方法

### ISSUE THREAD

**Issue by marktohark** [laravel-dojo/wagon#7]
mysql的port預設是33060
必須改成3306，才能被uwamp正常stop

**Comment by shengyou** [comment]
Uwamp 預設的 MySQL 是用 3306 port，當初是因為教學需求所以改成 33060，但改掉後的確會造成 Uwamp 的一些後遺症。若這對您造成不便，您可以依照需求去修改設定即可，謝謝。
